### ISSUE TITLE
Can't open write up?

### ISSUE THREAD

**Issue by dmadisetti** [ScholliYT/manim-frechet-distance#2]
I can't open your write up. Also thought you'd be intrested in this brief write up:

https://observablehq.com/@dmadisetti/frechet-distance

**Comment by ScholliYT** [comment]
Unfortunately, the docs are only available as zip archive containing a single pdf, due to GitHub Action artifact restrictions. Can you try to download the archive via this link: https://nightly.link/ScholliYT/manim-frechet-distance/workflows/build_docs/main/PDF.zip ?

However, the write up is still very incomplete. You may check again in like 1 week when deadline comes closer :rofl: 



I really like the interactive visualizations you provide in your write up. It's lots of fun playing around with it :smiley: Regarding your application I see improvement by ignoring the direction of paths. If you draw a clockwise circle and one counter clockwise their classical Fréchet distance is relatively large. However, the final image is very similar. Maybe add a note that it's recommended to draw in the same way / order.

**Comment by dmadisetti** [comment]
Cool! Will check back, I love manim stuff

Hmm. I think the circles in opposite directions is valid and comes from the definition of the reparameterizarion for the Frechet distance. The Alt/Godau paper backs this up in their discussion on free space (discussion on monotonicity) + explicitly stats this in definition 2:  https://www.researchgate.net/publication/220669649_Computing_the_Frechet_Distance_between_Two_Polygonal_Curves/link/00b7d518a824cbfe5f000000/download (says alpha(0) = a, alpha(1)=a').

But that's good! It means having an interactive illustrated that defined endpoints matter

**Comment by ScholliYT** [comment]
@dmadisetti Just wanted to let you know that the [presentation](https://scholliyt.github.io/manim-frechet-distance/Fr%C3%A9chet-Distance/) and [write up](https://nightly.link/ScholliYT/manim-frechet-distance/workflows/build_docs/main/PDF.zip) is finished now. Happy to hear you feedback.

**Comment by dmadisetti** [comment]
Wow, I need to learn some Manim.

Cool! Was this for a masters?

**Comment by ScholliYT** [comment]
Yes exactly. I made this paper and presentation for a seminar as part of my master degree. 
Manim is really cool. However, it also has some downsides, e.g. high rendering time. But is likely caused by my bad implementation and old version of Manim. If you plan on doing any presentations with Manim, I recommend not to go with the somewhat outdated [Manim-Editor](https://github.com/ManimCommunity/manim_editor) that I used, but instead the new [Main-Slides](https://eertmans.be/manim-slides/).
